### ISSUE TITLE
Adding regional Frisian channels

### ISSUE THREAD

**Issue by ghost** [Stevie-v/snp.220x132.transparent-white-ziggo#2]
Here are some additional regional Frisian channel logo's. Can you please add them as well. You only have to resize them to 220x132.

**Comment by Stevie-v** [comment]
Liever maak ik ze en mail ze ipv toe te voegen aan mijn github.
Groetjes Stefan

Verstuurd vanaf mijn iPad

Op 14 feb. 2021 om 19:52 heeft retrofan1979 <notifications@github.com> het volgende geschreven:

﻿

Here are some additional regional Frisian channel logo's. Can you please add them as well. You only have to resize them to 220x132. Thank you!

logo's.zip<https://github.com/Stevie-v/snp.220x132.transparent-white-ziggo/files/5978281/logo.s.zip>
